rpm-software-management/createrepo_c

CMakeLists.txt

Note that the correspond rpm specfile (e.g. Fedora one) will need a build dependency on bash-completion as well as adjustments for the dir and file names.

Bring bash completion install dir and filenames up to date with current bash-completion

---

examples/python/updateinfo_gen_01.py
examples/python/updateinfo_gen_02.py

Prior to this patch, both Python updateinfo generation examples yield:
```
Traceback (most recent call last):
File "updateinfo_gen_02.py", line 56, in <module>
generate()
File "updateinfo_gen_02.py", line 38, in generate
rec.issued_date = "2014-08-14 00:00:00"
TypeError: DateTime or None expected!
```

Python: Get the updateinfo generation examples working.

---

examples/python/simple_modifyrepo.py

I just ported bodhi over to createrepo_c (https://github.com/fedora-infra/bodhi/pull/128), and in the process wrote a basic Python example of inserting `updateinfo.xml` into repodata like `modifyrepo`

Examples: Add a simple modifyrepo python example

---

src/python/updaterecord-py.c

Some Red Hat advisories contain incomplete datetime information in "issued date" and/or "updated date" updateinfo.xml elements - YYYY-MM-DD instead of expected YYYY-MM-DD HH:MM:SS
attached patch prevents python Traceback on parsing such data.
Please consider adding the patch.
Best Regards
Jarek

fix traceback on non-complete datetime information (python)

---

examples/python/updateinfo_parsing.py
src/python/updaterecord-py.c
src/xml_dump_updateinfo.c
tests/python/tests/test_updateinfo.py

I think this issue is causing yum to complain:
https://github.com/fedora-infra/bodhi/issues/275

updateinfo: Fix a typo in the package release attribute

---

src/createrepo_shared.c
src/createrepo_shared.h

For [Unity Linux](http://unitylinux.com/index.php?id=about), we're using MUSL libc instead of glibc, so a great deal of non-standard and deprecated functions are not supported. This causes the createrepo_c build to fail because it uses `on_exit()`.
The `on_exit()` function is non-portable and is not available in all environments (notably Linux environments running on MUSL and Solaris based environments). 
Thus, the function call is swapped for the portable `atexit()` call.
The build and tests all pass after swapping `on_exit()` for `atexit()`.

Replace on_exit() call with atexit() call (Fixes FTBFS on Unity Linux)

---

.gitignore
src/cmd_parser.c
src/cmd_parser.h
src/createrepo_c.c
src/dumper_thread.c
src/dumper_thread.h
src/package.c
src/package.h

* createrepo_c supports now the "--split" option
* base url is set to "media:" by default if no "-u" option is set
* trailing double slashes will be cut off ( "media://" -> "media:")

Split option similar to python version of createrepo

---

src/mergerepo_c.c

I'd like to use mergerepo_c for cloning repository metadata, adding a pointer to the original package location. However this functionality would also require running mergerepo_c with a single repo argument.
This patch removes the requirement for two repo arguments.

Allow single repos in mergerepo_c

---

src/compression_wrapper.c
src/compression_wrapper.h

Per bzip2 documentation: "BZ2_bzReadClose does not call fclose on the underlying file
handle, so you should do that yourself if appropriate.".
This patch adds a INNERFILE element to CR_FILE to keep track of the FILE object so we
can properly close the file on cr_close.
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

Close BZ2 compressed files on cr_close

---

src/repomd.c
tests/python/tests/test_repomd.py

This will make sure that when set_record is called, all existing
records of the same type are removed.
It makes no sense to have multiple records of the same type,
and it actively breaks libhifs checksum validation.
Signed-off-by: Patrick Uiterwijk puiterwijk@redhat.com

Make set_record act like a setter

---

src/cmd_parser.c
src/cmd_parser.h
src/createrepo_c.c
src/dumper_thread.c
src/dumper_thread.h

Fixes Issue: https://github.com/rpm-software-management/createrepo_c/issues/58
This adds a flag to UserData for the cr_dumper_thread workers to record if theyt encountered an error, so main() can exit nonzero.

createrepo_c should exit nonzero if there are any errors.

---

src/parsehdr.c

Use 64 bit version of RPM tags (RPMTAG_LONGSIZE and RPMTAG_LONGARCHIVESIZE).
The LONG variant are available as extension tags if they are not physically
present in the header because we load header with HEADERGET_EXT. So we can
just use the LONG variants and ignore the old 32 bit tags.

Add large file support in RPM

---

src/parsehdr.c

Prior to RPM 4.12, RPM supported declaring `Recommends` using a hint on the `Requires` tag. The `Requires(missingok)` form was not broadly used, but historically in Mageia and Mandriva, `Suggests` aliased to this at build-time.

Correctly identify Requires(missingok) dependencies as legacy Recommends

---

CMakeLists.txt
README.md

At this point, we now have support for a legacy tag that has always existed in RPM (with `Requires(missingok)` support) and there's no good reason to have this disabled by default anymore, as it doesn't introduce extra dependencies of any kind, since the definitions are internal to `createrepo_c` anyway.

Enable support for processing legacy tags by default

---

src/mergerepo_c.c

Originally, the `pkg->name` was used as a key for `merged` GHashTable, but this `pkg->name` is freed later if the newer package is found in the same repository: https://github.com/hanzz/createrepo_c/blob/bf9a7e25363e010b50b076cad3505207a757c7d1/src/mergerepo_c.c#L887 . The g_hash_table_lookup then returned NULL.
This PR fixes it by creating copy of `pkg->name` as a key for `merged` GHashTable and frees it on this hash table destruction.

Fix missing packages in mergerepo_c in case multiple VR exists for single pkg in repo.

---

src/deltarpms.h.in

If you build createrepo_c with deltarpm support enabled, you get a ton of warnings about "CR_DELTA_RPM_SUPPORT redefined"

Fix "CR_DELTA_RPM_SUPPORT redefined" warnings

---

src/createrepo_shared.c
src/misc.c

New debug messages were added into GLib library. These messages come
from the "GLib" log domain and were not hidden in the standard and
quiet mode of the application.
This fix hides log messages regardless on source log domain.

Fix setup of logging (log domains) (RhBug:1645897)

---

doc/createrepo_c.8
src/cmd_parser.c
src/cmd_parser.h
src/createrepo_c.c
src/python/repomdrecord-py.c
src/repomd.c
src/repomd.h

Add `createrepo_c --set-timestamp-to-revision`, that set timestamps to the value given with `--revision` option. This way, executing `createrepo_c --revision xxx --set-timestamp-to-revision` twice on the same packages produce bit-by-bit identical results.
This is needed to [reproducibly build](https://reproducible-builds.org/) installation image. See also discussion on similar PR to createrepo, which lead to this specific option: https://github.com/rpm-software-management/createrepo/pull/9
Is there any place where test for `createrepo_c` call as a whole would fit? Since most of the logic is in `main()` (which have `exit()` at the end), it isn't suitable for unit tests...

Add option to create repodata reproducibly

---

src/cmd_parser.c
src/compression_wrapper.c
src/compression_wrapper.h
src/createrepo_c.c
src/deltarpms.c
src/deltarpms.h.in
src/dumper_thread.c
src/locate_metadata.c
src/mergerepo_c.c
src/misc.c
src/misc.h
src/modifyrepo_c.c
src/modifyrepo_shared.c
src/modifyrepo_shared.h
src/python/misc-py.c
src/python/repomdrecord-py.c
src/repomd.c
src/repomd.h
src/sqliterepo_c.c
src/threads.c
src/threads.h
tests/test_misc.c

This patch fixes cr_close() so it doesn't error if zck_end_chunk returns a positive number.

Add zchunk support to modifyrepo_c as well as for mergerepo_c and createrepo_c for extra metadata

---

tests/python/tests/CMakeLists.txt

To test on different OS versions, I run builds and tests in containers to which I install the minimal dependencies described in https://github.com/rpm-software-management/createrepo_c/blob/master/README.md. I saw a failure
```
-- Python install dir is /usr/lib64/python3.7/site-packages
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- nosetests program is nosetests-3.7
Command 'nosetests-3.7' doesn't exist! Using only 'nosetests' instead
-- Configuring done
[...]
```
and python tests were failing.
But I had python3-nose-1.3.7-21.fc29.noarch installed which brings
```
/usr/bin/nosetests-3
/usr/bin/nosetests-3.7
```
so defaulting to just `nosetests` was wrong.
The problem is in the `which` command which is not installed in container images by default. Since it is not documented as …

Find correct nosetests version even when which command is not available.

---

utils/make_rpm.sh

Addressing
```
Cleaning /root/rpmbuild//BUILD
Removing /root/rpmbuild//createrepo_c.spec
```

The .spec file typically lands under ~/rpmbuild/SPECS/.

---

.distributions
src/mergerepo_c.c

$ mkdir build
$ cd build
$ cmake -DCMAKE_BUILD_TYPE:STRING=DEBUG .. && make
$ mkdir repo1 repo2
$ cd repo1
$ wget http://linuxsoft.cern.ch/mirror/artifacts.elastic.co/packages/5.x/yum/5.5.0/elasticsearch-5.5.0.rpm
$ rpm -qpi elasticsearch-5.5.0.rpm
V4 RSA/SHA512 Signature, key ID d88e42b4: NOKEY
Name        : elasticsearch
Epoch       : 0
Version     : 5.5.0
Release     : 1
Architecture: noarch
Install Date: (not installed)
Group       : Application/Internet
Size        : 37317197
License     : 2009
Signature   : RSA/SHA512, Sat 01 Jul 2017 02:14:20 AM CEST, Key ID d27d666cd88e42b4
Source RPM  : elasticsearch-5.5.0-1-src.rpm
Build Date  : Sat 01 Jul 2017 01:20:44 AM CEST
Build Host  : packer-virtualbox-iso-1497797016
Relocations : /usr
Packager    : Elasticsearch
Vendor      : …

mergerepo_c: check if nevra is NULL and warn user about src.rpm naming.

---

src/locate_metadata.c

RFC 8089 Appendix B shows that the local file with empty authority has three slashes.
That same example appendix also shows `file:/path/to/file` but the original
code did not support it anyway.

When authority (host) is present, cr_get_local_metadata would not get path starting with /.

---

createrepo_c.spec

The obsolete should be applied only for Fedora 31+ where createrepo is
going to disappear, and for RHEL8.
The obsolete in EPEL-7 cannot be applied, because it obsoletes the core
package of RHEL7.

Make createrepo obsolete conditional

---

src/createrepo_shared.c

This reverts commit 4c2f4f48f259c19219d4d640884c5df7a7d4fc5e.
This re-fixes mockchain's ability to use createrepo_c. It was originally fixed by #108

Revert "Update logging function for standard mode"

---

src/createrepo_c.c
src/dumper_thread.c
src/dumper_thread.h

This PR aims to fix possible race condition when we use `--update` option (which loads old metadata but identical pkgs get only one record) and our new repo contains multiple occurrences of one pkg. 
Each occurrence of the one pkg is handled in separate thread and they all want to modify `location_href` and `location_base` of the old loaded single record.
With this change only the first thread gets the old record and every other duplicate thread has to load the package from disk again. This approach should have negligible slow down effect on runs with only a few or none duplicate pkgs, which I assume are much more common.

Prevent race condition when --update & we have duplicate pkgs (RhBug:1696808)

---

createrepo_c.spec

There is a condition to build with libmodulemd only on fedora >= 30 because on 29 libmodulemd 2.3.0 is available only in testing repo.

Add libmodulemd dependency to spec file

---

src/python/CMakeLists.txt
src/python/createrepo_c/__init__.py
src/python/createrepo_cmodule.c
src/python/updatecollection-py.c
src/python/updatecollectionmodule-py.c
src/python/updatecollectionmodule-py.h
src/updateinfo.c
src/updateinfo.h
src/xml_dump_updateinfo.c
src/xml_parser_internal.h
src/xml_parser_updateinfo.c
tests/fixtures.h
tests/python/tests/test_updatecollection.py
tests/python/tests/test_updatecollectionmodule.py
tests/python/tests/test_updateinfo.py
tests/test_xml_parser_updateinfo.c
tests/testdata/updateinfo_files/updateinfo_03.xml

Two features:
- add CMake support for python interpreter path, so its possible to either specify python version or path to interpreter
- add support for module element in updateinfo.xml

Add module element in updateinfo.xml

---

createrepo_c.spec

Since the creation of these symlinks is conditional, make their ownership
conditional as well.

Make ownership of createrepo, mergerepo, modifyrepo symlinks conditional

---

doc/mergerepo_c.8
src/koji.c
src/koji.h
src/mergerepo_c.c
src/mergerepo_c.h

When handling modules, we want a mode of operation for Koji that
handles the pkgorigins file but does not do any of the other
filtering or blocking that the --koji mode does.
Note: this patch doesn't need to change any code where the
pkgorigins file is actually populated, because it was already
conditionalized merely on the koji_stuff->pkgorigins pointer
being non-NULL, not driven by the cmd_options->koji.
Also includes a small patch to make the `koji_stuff_destroy()`
routine more resilient and handle when it's not fully constructed.

Add --pkgorigins mode

---

doc/createrepo_c.8
src/compression_wrapper.c
src/compression_wrapper.h
src/createrepo_c.c
src/createrepo_shared.c
src/createrepo_shared.h
src/deltarpms.c
src/dumper_thread.c
src/dumper_thread.h
src/mergerepo_c.c
src/modifyrepo_c.c
src/sqliterepo_c.c
src/threads.c
src/threads.h
src/xml_file.c
src/xml_file.h
tests/test_compression_wrapper.c
tests/test_xml_file.c

First two commits deal with RhBug: 1596211, where createrepo_c was generating repodata with wrong values in package count fileds if there were invalid packages. This happened because createrepo_c actually wrote there the task count (each package has its own task), but if some task failed no metadata for it was generated however it was still counted in the total package count. 
Because we know the actual package count only after all the package tasks have finished and compressed their metadata into repodata files we cannot simply change the package count value. In order to get to it we have decompress affected repodata files, change the value and compress them again. This is a significant performance blow.
The last two commits are dealing with some compiler warnings.

 Correct pkg count (RhBug:1596211) and warnings

---

createrepo_c.spec

Without this, under some circumstances it's not updating libmodulemd on the
system and if it gets 2.2.x or older, createrepo_c fails with undefined
symbol: modulemd_module_index_update_from_custom
Based on commit in Fedora downstream: https://src.fedoraproject.org/rpms/createrepo_c/c/40377017d0fc34d222a56ea1ad07ed63557a7a7d

Depend on the appropriate minimum version of libmodulemd

---

src/createrepo_c.c
src/deltarpms.c

GMutexes and GConds require their memory to be initialized to zeros, in createrepo_c.c the user_data struct which contains GMutexes and GConds is initialized to zeros when created. This however was not the case in deltarpms.c which caused createrepo_c to hang if `--deltas` was used.
This PR adds explicit initialization of GMutexes and GConds as it is safer and better adheres to the GLib Threads documentation.
(I didn't do this when I was [originally converting](https://github.com/rpm-software-management/createrepo_c/commit/6355d0f0433344a07f5903c6c126f623fb10e2f6) to the new API because I confused static and automatic allocation while reading the GLib docs)

Add explicit initialization of GMutexes and GConds (RhBug:1714666)

---

createrepo_c.spec
src/python/CMakeLists.txt
utils/setup_for_python_metadata.py

In order not to depend on scikit-build I added additional python setup
script (setup_for_python_metadata.py) which uses just setuptools and is
used to generate egg-info metadata during building of packages
python2/3-createrepo_c.
Related to #145

Add missing python metadata to python2/3-createrepo_c (RhBug:1695677)

---

src/createrepo_c.c
src/dumper_thread.c
src/dumper_thread.h

As specified in the man page: file created by --read-pkgs-list should contain a list of only actually read packages not all the tasks createrepo_c creates.
This way it also works with --update to create a list of only updated packages.
This addresses root cause of https://github.com/rpm-software-management/createrepo_c/issues/130.

Fix --read-pkgs-list to only list actually read packages

---

README.md
doc/createrepo_c.8
doc/mergerepo_c.8
src/cmd_parser.c

The first commit addresses https://github.com/rpm-software-management/createrepo_c/issues/79.

Update documentaition: retain-old-md, compatibility, koji simple, merge methods

---

doc/Doxyfile.in.in

This change avoids file conflicts when installing createrepo_c-devel
package for i686 and x86_64 architectures in parallel.
After switching the timestamps off the documentation html files are
identical for both builds and rpm does not consider them conflicting any
more.
https://bugzilla.redhat.com/show_bug.cgi?id=1731050

Switch off html timestamps on documentation (RhBug:1731050)

---

src/xml_file.c

https://bugzilla.redhat.com/show_bug.cgi?id=1750673

Fix search in string with missing terminating zero (RhBug:1750673)

---

src/dumper_thread.c

Cache files are created with tempfile mechanism which uses default mode
of 0600, this commit changes their mode to the one specified by umask.
Original reason for this is sharing cache between multiple users
updating one repository.
https://bugzilla.redhat.com/show_bug.cgi?id=1686812
This also unifies behavior with original createrepo.

Honor umask on cache files (RhBug:1686812)

---

src/cmd_parser.c
src/cmd_parser.h
src/createrepo_c.c

the old python based createrepo exported all changelog entries to the
other.xml. createrepo_c limits to 10 entries.
This patch is an attempt to get all entries into the other.xml without
changing the default behavior of createrepo_c via using the
--compatibility option.

export all changelog entries in compatibility mode

---

src/compression_wrapper.c

If the input metadata file for modifyrepo_c was a symlink the
program failed to detect compression type. This patch instructs
libmagic to follow the symlinks when guessing the mime type.
Let modules.yaml be a symlink:
$ modifyrepo_c ./modules.yaml ./repodata
Cannot open ./modules.yaml: Cannot detect compression type
https://bugzilla.redhat.com/show_bug.cgi?id=1776399

Libmagic to follow symlinks (RhBug:1776399)

---

src/python/updatecollectionpackage-py.c
src/updateinfo.c
src/updateinfo.h
src/xml_dump_updateinfo.c
src/xml_parser_updateinfo.c
tests/python/tests/test_updatecollectionpackage.py
tests/python/tests/test_updateinfo.py
tests/test_xml_parser_updateinfo.c
tests/testdata/updateinfo_files/updateinfo_01.xml

As discussed here https://github.com/rpm-software-management/createrepo_c/pull/187 adding restart_suggested to packages.
Also extended the unit tests with the new field as well.

Add restart_suggested to updatecollectionpackage

---

src/createrepo_c.c

Make sure that we use patterns the same way for directory walk (we used
to match full relative directory) and for explicit --pkglist (we used to
match only the rpm basename).  So from now on, the relative path is
tested for match.

Sync --excludes matching for dir-walk vs. --pkglist

---

createrepo_c.bash
doc/createrepo_c.8
src/cmd_parser.c
src/cmd_parser.h
src/createrepo_c.c
src/dumper_thread.c
src/load_metadata.c
src/load_metadata.h
src/misc.c
src/misc.h

```
createrepo_c: add --recycle-pkglist option
This option is useful e.g. for very large repositories in copr [1] where
we need to update the repodata after each package build or package
removal.  Re-generating everything from scratch with --update is simply
too expensive (actually even the directory traversal is) so the only
only viable option would be to maintain complete list of packages
manually, and use '--pkglist --no-stat'.
With '--recycle-pkglist' we can avoid the additional work with separate
pkglists.  Adding new builds can be done just like
$ createrepo_c --no-stat --update --recycle-pkglist --pkglist <sth>
and removing something can be done with
$ createrepo_c --no-stat --update --recycle-pkglist --exclude <sth>
[1] https://pagure.io/copr/copr/pull-request/1150
```

recycle pkglist with --update

---

src/xml_dump_updateinfo.c
tests/python/tests/test_updateinfo.py
tests/python/tests/test_updaterecord.py

Elements <restart_suggested> and both <reboot_suggested> were previously
outputed just as an empty element which meant they are true, this patch
changes it to explicitly output:
<reboot_suggested>True</reboot_suggested>.
However we still don't output False values, in that case the element is
simply omitted.
https://bugzilla.redhat.com/show_bug.cgi?id=1772466

Switch updateinfo to explicitly include bool values (RhBug:1772466)

---

doc/createrepo_c.8
src/cmd_parser.c
src/createrepo_c.c
src/locate_metadata.c
utils/gen_rst.py

This fixes a crash that occurred when specifying `--update-md-path` with invalid path.
https://bugzilla.redhat.com/show_bug.cgi?id=1762697
And this PR contains tests for this:
https://github.com/rpm-software-management/ci-dnf-stack/pull/757
I also tried to make the documentation for the option more friendly (which led me to updating the script which generates it to python3).

Fix crash when passing invalid path to --update-md-path (RhBug:1762697)

---

src/createrepo_shared.c

global_exit_status is used by failure_exit_cleanup function, which is
setup by atexit(), to determine whether to clean up temp metadata.
This resolves issue https://github.com/rpm-software-management/createrepo_c/issues/188

Set global_exit_status on sigint so that .repodata are cleaned up

---

src/python/updatecollectionpackage-py.c
src/python/updaterecord-py.c
src/updateinfo.c
src/updateinfo.h
src/xml_dump_updateinfo.c
src/xml_parser_updateinfo.c
tests/python/tests/test_updatecollectionpackage.py
tests/python/tests/test_updateinfo.py
tests/test_xml_parser_updateinfo.c
tests/testdata/updateinfo_files/updateinfo_01.xml
tests/testdata/updateinfo_files/updateinfo_03.xml

Adds relogin_suggested field and enables epoch time format in Python API for issued_date field.
Also extends unit tests for these features.
https://bugzilla.redhat.com/show_bug.cgi?id=1779751

Finish support for OpenSUSE updateinfo (RhBug:1779751)

---

tests/test_xml_parser_filelists.c

This problem could have caused random test failures.

Fix test helper function by adding terminating null to result

---

src/python/updatecollection-py.c
tests/python/tests/test_updatecollection.py

When assigned updateCollectionModule goes out of scope it gets freed
because its references drop to 0, this resulted in bogus data because
the memory was still being used.
This patch ensures we pass the updateCollectionModule by value (it gets
copied on assignment) just like everywhere else in the updateinfo api.
Also adds a test for this case.
https://bugzilla.redhat.com/show_bug.cgi?id=1821781

Copy updateCollectionModule on assignment to prevent bogus data (RhBug:1821781)

---

doc/mergerepo_c.8
src/mergerepo_c.c
src/mergerepo_c.h

This is a separate option that does a subset of --koji functionality:
For specified --archlist it adds multilib arches and then expands all of
them.
I have also created some tests for our CI stack: https://github.com/rpm-software-management/ci-dnf-stack/pull/821
For issue: https://github.com/rpm-software-management/createrepo_c/issues/213

Add --arch-expand option

---

src/createrepo_c.c

When there are no packages in exisiting repodata and --update with
--recycle-pkglist is used createrepo_c shouldn't do the dir walk, the
situation is the same as using empty pkglist.
Fixes issue: https://github.com/rpm-software-management/createrepo_c/issues/222

Never do dir walk when --recycle-pkglist specified

---

doc/createrepo_c.8
src/cmd_parser.c
src/cmd_parser.h
src/createrepo_c.c
utils/gen_rst.py

The new behavior is described in the associated bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1795936#c3
This resolves https://github.com/rpm-software-management/createrepo_c/issues/134 (except it doesn't do any validation against present rpms, the created repository can have completely unrelated modular metadata and packages in it).
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/860

Add module metadata support to createrepo_c (RhBug:1795936) 

---

src/createrepo_c.c
src/xml_parser.c
tests/python/tests/test_xml_parser.py

If string passed to xmlParseChunk (function froml libxml2) is too big the function errors out, its safer to parse the snippet in
smaller parts.
Also adds a unit test for this case.
https://bugzilla.redhat.com/show_bug.cgi?id=1859689
The third commit is unrelated and fixes an issue of accessing possible NULL pointer to `tmp_err`.

Parse xml snippet in smaller parts (RhBug:1859689)

---

doc/createrepo_c.8
doc/mergerepo_c.8
doc/modifyrepo_c.8
doc/sqliterepo_c.8
utils/gen_manpage.sh
utils/gen_rst.py

Hi,
First, thanks a lot for writing and maintaining this implementation of createrepo!
What do you think about this trivial patch that corrects the invocation of the ".TH" (title) macro, adding the missing section 8 parameter? It seems that whatever generated the troff file was aware that there should have been another value there - there are two spaces between the program name and modification date parameters - but it was somehow invoked in such a way as to not place anything there, not even an empty string in troff syntax.
BTW, are these manual pages really generated from a ReST source? If so, where is that source, and how is the generation performed? Or have they been written up once, converted to troff format, and then edited directly in troff format from then on? If it is the latter, …

Add the section number to the manual pages.

---

src/python/contentstat-py.c
src/python/locate_metadata-py.c
src/python/package-py.c
src/python/repomd-py.c
src/python/repomdrecord-py.c
src/python/typeconversion.c
src/python/typeconversion.h
src/python/updatecollection-py.c
src/python/updatecollectionmodule-py.c
src/python/updatecollectionpackage-py.c
src/python/updaterecord-py.c
src/python/updatereference-py.c

fixes: #230 (bz [#1893459](https://bugzilla.redhat.com/show_bug.cgi?id=1893459))
Additionally fixes a couple of other memory leaks.  Completely removes the ```PyObject_ToStrOrNull()``` function which cannot possibly work without leaking memory.

Fix memory leaks in python extension code

---

src/python/compression_wrapper-py.c

PyArg_ParseTuple() and formats which use # require the PY_SSIZE_T_CLEAN
macro since python 3.10
For: https://github.com/rpm-software-management/createrepo_c/issues/234
This should also fix: https://bugzilla.redhat.com/show_bug.cgi?id=1891785

Fix Python deprication (PY_SSIZE_T_CLEAN)

---

src/createrepo_c.c
src/misc.c
src/misc.h
src/modifyrepo_shared.c
src/python/misc-py.c
src/threads.c
tests/test_misc.c

In commit 79975df `in_dst` argument was changed to actually return allocated 
string with the final destination if the input `in_dst` was NULL, a direcotry or had
a different compression suffix. However the value is actually never used
anywhere and it is causing a memory leak.
This is a c API change but since we are reverting to previous IMO better API and 
before it was changed without problems I believe it is worth it.
The PR also contains a fix for suffix changes and one warning fix.

Revert back to old API of cr_compress_file_with_stat and cr_compress_file

---

src/createrepo_c.c
src/createrepo_shared.c

createrepo_c was removing `.repodata` if `exit_val` was se to failure.
Problem is `exit_val` is set only on a couple of places so most of the
failures (no matter how rare) leave `.repodata` behind.
However because on a successful run `.repodata` is renamed to normal
output `repodata` we know that if `.repodata` are present there was an
error and we can delete them.
https://bugzilla.redhat.com/show_bug.cgi?id=1906831

Never leave behind .repodata lock on exit (RhBug:1906831

---

.github/workflows/python_ci.yml
README.md
createrepo_c.spec

Add some automation for the following:
* Build createrepo_c + documentation + tests the "standard way" with the cmake workflows documented in the readme
* Build createrepo_c as a Python package, install it, and run the Python tests using pytest
* When a new release is tagged, automatically build and push the packages to PyPI
* This would require a little bit of setup -- the RPM team or someone from the RPM team would need to be added as a co-maintainer on the createrepo_c Python package, and their credentials added to the "secrets" storage

Add automated Github Actions CI

---

tests/python/tests/test_crfile.py

More details in: https://github.com/rpm-software-management/createrepo_c/issues/259

Fix valgrind warnings caused by subprocess calls.

---

.github/workflows/ci-python.yml

python3-pip is just a weak dependence of python3. In case the python3
was installed without weakdeps in base container and did not get
upgraded during `dnf builddep`, the pip command is missing.

CI: Add pip to packages Python CI installs

---

createrepo_c.spec

Enable libmodulemd in RHEL >= 8 (RhBug:1816753)
Fix case when 0%{?fedora} or 0%{?rhel} is undefined. For example, on
RHEL, 0%{?fedora} is undefined and "0%{?fedora} < 29" resolves to true,
although you'd expect it to be false.

Fix conditionals in spec

---

src/dumper_thread.c
src/misc.c
src/xml_parser_filelists.c
src/xml_parser_primary.c

Fixes defects reported for version: `createrepo_c-0.17.2-2.el9` compared to `createrepo_c-0.16.2-2.el9`.
- check we actually got a filename in xml parsers and in decompression
function
- use g_malloc0 as we do in other places (it also takes care of checking
if allocation was successful)

Fix additional covscan warnings

---

src/createrepo_c.c
src/mergerepo_c.c
src/python/xml_dump-py.c
src/repomd.c
src/sqliterepo_c.c
src/xml_file.c

Previous approach was too complicated, slow and ultimately unnecessary.
If an invalid file passes as allowed it is caught later when loading the
module metadata. There is no need to slow down checking of each
path/package with compression validation.
For: #275
I have also included a couple of memory leaks reported by covscans, 
these usually happen in error handling so they are not a big priority.

Simplify checking for allowed modulemd metadata files

---

src/checksum.c
src/misc.c

Zero init buffer to prevent use of garbage values if input is too short

---

doc/createrepo_c.8
src/cmd_parser.c
src/cmd_parser.h
src/createrepo_c.c
src/locate_metadata.c
src/locate_metadata.h
src/repomd.c
src/repomd_internal.h
tests/python/tests/test_repomdrecord.py

= changelog =
msg: Switch default of --keep-all-metadata to TRUE and add --discard-additional-metadata
type: enhancement
resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1992209
`--keep-all-metadata` controls whether to keep additional metadata (such as comps, updateinfo, modules..) during a run with `--update`. With this PR they will be kept by default whereas before `--keep-all-metadata` had to be used.
We might want this because modular repositories really break without the `modules.yaml`.

Default --keep-all-metadata to TRUE and add --discard-additional-metadata

---

doc/createrepo_c.8
src/cmd_parser.c
src/createrepo_c.c

= changelog =
msg: Use --error-exit-val option by default
type: enhancement
resolves: https://github.com/rpm-software-management/createrepo_c/issues/302

Use --error-exit-val option by default

---

src/python/createrepo_c/__init__.py

There is no way to access parser warnings from the higher-level API.

Make parse warnings visible through cr.Repomd(), cr.UpdateInfo()

---

examples/python/repodata_parsing.py
src/python/xml_parser-py.c
src/xml_parser.h
src/xml_parser_main_metadata_together.c
tests/python/tests/test_xml_parser.py
tests/test_xml_parser_main_metadata_together.c

The option was causing issues when repository has duplicate packages and
it was providing little value. All repos should really have the same
order of packages in primary, filelists and other metadata.
For: https://github.com/rpm-software-management/createrepo_c/issues/305
It also includes 2 fixes for memory leaks originally from https://github.com/rpm-software-management/createrepo_c/pull/295

Remove allow_out_of_order option and fix couple of leaks

---

src/xml_parser.c
src/xml_parser_filelists.c
src/xml_parser_internal.h
src/xml_parser_other.c
src/xml_parser_primary.c
src/xml_parser_repomd.c
src/xml_parser_updateinfo.c
tests/python/tests/fixtures.py
tests/python/tests/test_xml_parser.py
tests/testdata/modified_repo_files/repo_01_ampersand-filelists.xml
tests/testdata/modified_repo_files/repo_01_ampersand-other.xml
tests/testdata/modified_repo_files/repo_01_ampersand-primary.xml
tests/testdata/modified_repo_files/updateinfo_ampersand.xml

Repodata don't use any custom entities but libxml2 enforces some in
order to have a valid xml document when saved (`<`, `>`, `&`,...)
http://xmlsoft.org/entities.html
When createrepo_c runs with `--update` it parses repodata which can
contain such entities (`&amp;` for `&`). We want to substitute them back
so when the data is used again it doesn't get re-escaped.
https://github.com/rpm-software-management/createrepo_c/issues/286

Enable entity substitution when parsing xmls

---

src/xml_parser.c

Without this patch testing after build fails with the following error message:
```[   38s] /home/abuild/rpmbuild/BUILD/createrepo_c-0.20.0/build/tests/python/tests/run_unittests.sh: line 1:  2327 Aborted                 LD_LIBRARY_PATH=/home/abuild/rpmbuild/BUILD/createrepo_c-0.20.0/build/src/: PYTHONPATH=/home/abuild/rpmbuild/BUILD/createrepo_c-0.20.0/build/src/python/ WITH_LIBMODULEMD=ON /usr/bin/python3 -m unittest discover -s /home/abuild/rpmbuild/BUILD/createrepo_c-0.20.0/tests/python/tests/../```
on openSUSE 15.3 and several other SUSE distros

fix memory allocation in unescape_ampersand_from_values

---

src/CMakeLists.txt
src/createrepo_shared.h

This module contains some useful functions which are already documented in `createrepo_c`'s generated API documentation.

Install header for createrepo_shared module

---

src/createrepo_shared.c
src/dumper_thread.c
src/misc.c
src/parsepkg.c

Either the call to `g_strerror` or the GLib logging calls have been changing the value of `errno` before it is used to set the error message in `g_set_error`. This resulted in a correct error message being logged, but an incorrect message being reported to the caller.
This change resolves the issue by calling `g_strerror(errno)` once and re-using the same message to pass to both the logging function and `g_set_error`.
Fixes: #320

Update errno usage to fix incorrect GError messages

---

src/createrepo_c.c
src/dumper_thread.c
src/dumper_thread.h

Return an error code and print a message when more than one package have
the same NEVRA.
closes #307

createrepo_c shouldn't silently produce duplicate-NEVRA repos

---

src/xml_file.c

Fixes build with Clang 16.
Bug: https://bugs.gentoo.org/875698
Signed-off-by: Sam James <sam@gentoo.org>

Include <rpm/rpmstring.h> for rasprintf

---

src/cmd_parser.c
src/cmd_parser.h
src/createrepo_c.c
src/dumper_thread.c
src/dumper_thread.h
src/package.h
src/threads.c

This is follow-up for #307.  Unfortunately, the parallel processing performance degrades a bit
with the "keep-last" option.
Motivation for Copr: https://pagure.io/copr/copr/issue/840
We can tweak this in the future (keep latest pkg per mtime, keep the first one, etc.).

Add --duplicated-nevra "keep-last" option, and --delayed-dump

---

createrepo_c.spec

For building on EL7 with libmodulemd we need to use package libmodulemd2 from epel repo.

Add support for libmodulemd on EL7

---

src/createrepo_c.c

Starting with glib-2.70.0, the g_pattern_match() function has been deprecated in favor of g_pattern_spec_match().  Still support building with older versions of glib, just add some preprocessor handling to eliminate the build time deprecation warning.
msg: Use g_pattern_spec_match() with glib >= 2.70.0 type: enhancement
Signed-off-by: David Cantrell <dcantrell@redhat.com>

Use g_pattern_spec_match() with glib >= 2.70.0

---

src/xml_file.c

This reverts commit 696a7653c4c9c9ab8e0cd2e7e24dbda9ec51a2b8.
Already added by commit d8da644c45bec1429d600c619ce4e47af5906ef8.

Revert "include rpm/rpmstring.h"

---

src/cmd_parser.c

Without this patch the following error occurs:
"Invalid byte sequence in conversion input"
when you try something like
```
createrepo_c --repo fööbär foobar
```
setlocale is required to ensure that NON-ASCII chars can be parsed SEE https://developer-old.gnome.org/glib/unstable/glib-running.html#setlocale for further information

fix errors while parsing utf8 chars in cli options

---

.github/workflows/release-python.yml

Currently `Python Release` workflow fails due to conflicting request when a `Pygments` distro package is tried to be uninstalled when pip dependencies are being resolved. In this case we can install the dependencies from distro packages instead.

Install distro packages instead of pip ones when available

---

src/dumper_thread.c

When using --update, --skip-stat and --reycle-pkglist we do not want to rewrite location_base but keep all the metadata for a package
By default createrepo_c removes the location_base that was already set in the metadata using the null value from the parameter
Skip it and keep the location_base when it's null (and if both are null it shouldn't change the current behaviour)

Keep location_base on update if no baseurl defined in args

---

src/cmd_parser.c
src/compression_wrapper.c
src/createrepo_c.c
src/createrepo_shared.h
src/error.h
src/locate_metadata.c
src/mergerepo_c.c
src/misc.h
src/modifyrepo_c.c
src/modifyrepo_shared.c
src/repomd.c
tests/python/tests/test_parsepkg.py
utils/speed_test.sh

Corrects a typo/mixed case in several locations, to fix #358

Correct 'doesn't exists' to 'doesn't exist' in several locations

---

src/cmd_parser.c

This resolves the following error with older versions of gcc: 
```
| /srv/storage/alex/yocto/build-32/tmp/work/x86_64-linux/createrepo-c-native/0.21.1-r0/git/src/cmd_parser.c: In function ‘duplicated_nevra_option_parser’: | /srv/storage/alex/yocto/build-32/tmp/work/x86_64-linux/createrepo-c-native/0.21.1-r0/git/src/cmd_parser.c:76:32: error: parameter name omitted
|    76 | duplicated_nevra_option_parser(const gchar *,
|       |                                ^~~~~~~~~~~~~
| /srv/storage/alex/yocto/build-32/tmp/work/x86_64-linux/createrepo-c-native/0.21.1-r0/git/src/cmd_parser.c:78:32: error: parameter name omitted
|    78 |                                gpointer,
|       |                                ^~~~~~~~
```

src/cmd_parser.c: add a missing parameter name

---

src/python/createrepo_c/__init__.py
src/python/package-py.c
src/python/typeconversion.c
tests/python/tests/test_xml_parser.py

The change was introduced in https://github.com/rpm-software-management/createrepo_c/pull/316
For: https://github.com/rpm-software-management/createrepo_c/issues/360

Fix change in python API of package files

---

src/compression_wrapper.c

Declaration is not a statement.
This seems to work with newer versions of GCC but the C language standard only allows statements to follow a label.
For: https://github.com/rpm-software-management/createrepo_c/issues/369

Fix: error: a label can only be part of a statement

---

src/createrepo_c.c
src/mergerepo_c.c
src/mergerepo_c.h
src/modifyrepo_shared.c

It also changes mergerepo_c so that option `--compress-type` sets compression for all repository files (except sqlite dbs).
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1311
Compression for sqlite dbs remains the same.
This is part of: https://fedoraproject.org/wiki/Changes/createrepo_c_1.0.0

Switch the default compression type to zstd

---

createrepo_c.spec

Disable drpm support on fedora >= 39
RhBug: https://bugzilla.redhat.com/show_bug.cgi?id=2213212

Disable drpm support on fedora >= 39 (RhBug:2213212)

---

src/createrepo_c.c
src/load_metadata.c
src/mergerepo_c.c
src/metadata_internal.h

We no longer create uncompressed groupfile. There is only one compressed
groupfile with type "group" (in repomd.xml). Therefore we don't need to copy the groupfile, compressing it
is enough.
Follow up for change in createrepo_c: https://github.com/rpm-software-management/createrepo_c/pull/373
This is for: https://fedoraproject.org/wiki/Changes/createrepo_c_1.0.0
Test: https://github.com/rpm-software-management/ci-dnf-stack/pull/1340
(This was causing a test fail in `ci-dnf-stack`)

mergerepo_c: create only one groupfile metadata

---

src/misc.h
src/xml_dump_deltapackage.c
src/xml_dump_updateinfo.c

Enabling more warnings and pedantic checking against ISO C17 conformance revealed some errors.  This patch just cleans up things to get the source compiling correctly under a wider range of gcc and clang versions.
Fixes: #357

Fix some invalid C code to cover a wider ranger of compilers

---

src/CMakeLists.txt
src/misc.c

Some systems (e.g., glibc Linux systems) required _XOPEN_SOURCE be set to >= 500 in order to expose the nftw() function.  Other systems, such as macOS, do not require this definition.  When using feature macros like this, it is better to not define them explicitly in source code but rather define them dynamically at build configuration time based on what the build system presents.
This patch removes the explicit definiton of _XOPEN_SOURCE from src/misc.c and adds a block to src/CMakeLists.txt to determine if _XOPEN_SOURCE must be defined in order to use nftw().  If it is required, I set it to 700 which is what is required for the Python code as well and it avoids a redefinition warning.
Fixes: #374

Detect need for _XOPEN_SOURCE for nftw() in CMakeLists.txt

---

src/metadata_internal.h

This function is used in code which is not conditional under WITH_LIBMODULEMD therefore the declaration should also match its definition scope
Fixes build issues flagged by clang
src/createrepo_c.c:850:16: error: incompatible integer to pointer conversion initializing 'gchar *' (aka 'char *') with an
expression of type 'int' [-Wint-conversion]
|   850 |         gchar *compressed_path = cr_compress_groupfile(cmd_options->groupfile_fullpath, tmp_out_repo, compression);
|       |                ^                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Move cr_compress_groupfile outside WITH_LIBMODULEMD

---

src/python/typeconversion.c
tests/python/tests/test_package.py

The fix in https://github.com/rpm-software-management/createrepo_c/pull/362 resolved the situation when getting pkg files from python. We need to also fix setting pkg files.
Make the digest optional in order to still support files without it.

Python API: Fix a crash when setting pkg files

---

CMakeLists.txt
createrepo_c.spec
src/createrepo_c.c
src/deltarpms.c
src/dumper_thread.c
src/dumper_thread.h
src/misc.c
src/sqliterepo_c.c
src/xml_file.c
tests/test_compression_wrapper.c
tests/test_koji.c
tests/test_load_metadata.c
tests/test_locate_metadata.c
tests/test_misc.c
tests/test_modifyrepo_shared.c
tests/test_sqlite.c
tests/test_xml_dump.c
tests/test_xml_dump_primary.c
tests/test_xml_parser_filelists.c
tests/test_xml_parser_main_metadata_together.c

This should fix most of the detected problems. There still are several left that I wasn't able to figure out and I am not sure if they are problems in createrepo_c or if they are not false positives:
- Leaks in python unittest (this might be a python loading module problem - we see something like this even in dnf)
- Leaks in `g_option_context_parse`
- Inconsistent leaks from `xmlBufferCreate` from `cr_xml_dump_primary`
- Leak of `sqliterepocmdoptions_new`
Closes: https://github.com/rpm-software-management/createrepo_c/issues/384

Add `sanitizers` build option, fix bunch of detected problems

---

src/createrepo_c.c
src/misc.c
src/xml_dump_repomd.c

This fixes a crash when time_t is 64bit and also
fL::wqixes format specifier mismatch warnings as well while here
e.g.
warning: format '%ld' expects argument of type 'long int', but argument 2 has type 'time_t'

Adjust printf formats for 64bit time_t on 32bit systems

---

src/createrepo_c.c

The existing code is non-idiomatic, and as it so happens EL9 currently defines this macro unexpectedly despite not having the proper API, so we replace this with the idiomatic approach to make it actually work.
https://issues.redhat.com/browse/RHEL-12941
https://github.com/rpm-software-management/createrepo_c/pull/342/files#r1357391661

Fix building on EL9

---

CMakeLists.txt
createrepo_c.spec
src/compression_wrapper.c
tests/test_compression_wrapper.c

Since zstd is the default compression building without leads to broken default runs.
Alternative to: https://github.com/rpm-software-management/createrepo_c/pull/379

Don't allow building without zstd

---

src/compression_wrapper.c

This requires a good amount of saving due to larger dictionary size with only marginal more time effort for compression. decompression time is unaffected.

Set compression level for zstd to level 10

---

doc/createrepo_c.8
src/cmd_parser.c
src/createrepo_c.c
src/modifyrepo_c.c
src/xml_dump.c
src/xml_dump.h
src/xml_dump_deltapackage.c
src/xml_dump_filelists.c
src/xml_dump_internal.h
src/xml_dump_other.c
src/xml_dump_primary.c
src/xml_dump_repomd.c
src/xml_dump_updateinfo.c

The indentation might be pretty, but it also adds a few percent of compressed size to the metadata. for production use a --no-pretty can now be set that reduces the amount of blanks in the repodata xml.

Add a --no-pretty option to reduce repo metadata size

---

src/compression_wrapper.c

In the previous commit we changed the compression level from 9 to 10 for the "legacy" primary.xml.zst. Set the same level for the zck.

Set same compression level for zck

---

createrepo_c.spec

Due to the existing support of DRPM in Fedora 39 and EPEL 7, we need to still maintain it for some time.
Closes #398.

Keep support for DRPM in Fedora

---

src/sqlite.c

fail here: https://copr.fedorainfracloud.org/coprs/rpmsoftwaremanagement/dnf-nightly/build/6668781/
pass here: https://copr.fedorainfracloud.org/coprs/nsella/dnf5_stack_fix_xml/build/6670347/

build: Restore compatiblity with libxml2-2.12.0

---

createrepo_c.spec

This helps with minimizing downstream-patches for custom createrepo_c builds with bumped Epoch (useful for the Copr team, we need to maintain a custom createrep_c build with legacy hashes enabled, and bumped epoch protects us from random upgrades to the system-default version).

Use Epoch-friendly sub-package interdependencies

---

CMakeLists.txt
README.md
createrepo_c.spec
src/sqlite.c

SQLite shared cache is discouraged and SQLite can be compiled without a support for it. If the support is disabled,
sqlite3_enable_shared_cache() function is not provided by the library and building createrepo_c fails.
This patch moves from sqlite3_enable_shared_cache() to a newer sqlite3_open_v2(,, SQLITE_OPEN_SHAREDCACHE,) API available since SQLite 3.6.18 (2009-09-11).
This has four effects:
(1) Building passes even if shared cache is not supported by SQLite.
(2) If the support is not available at run-time, SQLite keeps working.
(3) The shared cache is only enabled on connections createrep_c library opens. It does not affect SQLite connections made by different libraries or an application.
(4) sqlite >= 3.6.18 is required for building. …

SQLite: Enable shared cache on connection level

---

src/xml_parser.c
src/xml_parser_main_metadata_together.c

libxml2-2.12.0 started to return errors as a pointer to a constant structure and GCC 13.2.1 started to warn like this:
/home/test/createrepo_c/src/xml_parser.c: In function ‘cr_xml_parser_generic’: /home/test/createrepo_c/src/xml_parser.c:204:35: warning: initialization discards ‘const’ qualifier fro m pointer target type [-Wdiscarded-qualifiers]
204 |             xmlErrorPtr xml_err = xmlCtxtGetLastError(parser);
|                                   ^~~~~~~~~~~~~~~~~~~
This patch fixes it.

Fix const-correctness with libxml2-2.12.0

---

src/createrepo_c.c

Defaulting to keeping all changelogs, while accurate to the behavior of legacy createrepo, can result in terrible behaviors for some repositories, making them potentially too large to be usable (libsolv may segfault, I'm not sure about YUM, but both end up unpacking the data on the root partition potentially causing it to run out of space).
The most problematic packages are ones like openssl, glibc, and the kernel which ship with 20+ years of changelog history.  If the repo contains many versions of these packages, the impact is tremendous.  If a user needs full changelog history, they ought to consult `rpm --qa --changelog`
This behavior of the --compatibility flag was never explicitly documented.
closes #318

Default changelog limit restored for --compatibility

---

src/cmd_parser.c
src/createrepo_c.c

* --compatibility will enable sqlite metadata by default
* --compatibility will leave group metadata uncompressed rather than defaulting to the same compression as everything else
I believe this covers the bases in terms of ensuring createrepo_c 1.0 can still generate repos consumable by ancient RHEL / SUSE without too much effort.
I don't add  `group_gz` (separate gzip-compressed group metadata) back - this is aiming for minimal additional complexity and `group_gz` simply isn't worth it.  It's usually a relatively tiny metadata file anyway.

Extend the --compatibility flag to cover other defaults

---

createrepo_c.spec

Based on: https://github.com/rpm-software-management/dnf5/pull/1254.
See also: https://github.com/rpm-software-management/dnf5/issues/1252.

build: Adapt to changes in Fedora packaging of bash-completion

---

src/xml_dump.c

Relates to issue #424.
tested with packages https://download.copr.fedorainfracloud.org/archive/issues/copr-3163/ , as referenced 
https://github.com/fedora-copr/copr/issues/3163
now I got (as expected) these lines [1]  the problem on nodejs-electron.spec was here [2] 
[1] 
createrepo_c .
```
Directory walk started
Directory walk done - 5 packages
Temporary output repo path: ./.repodata/
Pool started (with 5 workers)
Package RPM license AFL-2.0 AND Apache-2.0 AND blessing AND BSD-2-Clause AND BSD-3-Clause AND BSD-Protection AND BSD-Source-Code AND bzip2-1.0.6 AND IJG AND ISC AND LGPL-2.0-or-later AND LGPL-2.1-or-later AND MIT AND MIT-CMU AND MIT-open-group AND (MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later) AND MPL-2.0 AND OpenSSL AND SGI-B-2.0 AND SUSE-Public-Domain AND X11 AND Zlib …
```

print where and when cr_hascontrollchars is true

---

createrepo_c.spec

We already use it in F41 package. I'm only not sure since when %py3_shebang_fix is supported.

spec: Package Python examples

---

src/compression_wrapper.c

Covscan reported:
createrepo_c-1.1.2/src/compression_wrapper.c:197: error[resourceLeak]: Resource leak: file
It's a real bug and this patch fixes it.
Resolves: https://issues.redhat.com/browse/RHEL-45645

Fix a file descriptor and memory leak in an error path of cr_detect_compression()

---

src/python/createrepo_c/__init__.py
src/python/xml_parser-py.c
src/xml_parser_main_metadata_together.c
tests/python/tests/test_xml_parser.py
tests/test_xml_parser_main_metadata_together.c

Supplying a NULL value as a filelists or other "path" argument ought to work.  But primary metadata is always required.
closes #423

Allow incremental parsing without filelists or other xml

---

.gitignore
createrepo_c.spec
utils/make_rpm.sh
utils/make_tarball.sh

Reported as #436 
Some small fixes of generating rpm packages

Fix rpm build script

---

setup.py

Pulp needed this overridden at one point, but not anymore.

Remove LEGACY_HASHES override from setup.py

---

src/compression_wrapper.c

STDOUT_FILENO is defined in unistd.h, see [POSIX](https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/unistd.h.html).
This is required on FreeBSD.

Include unistd.h for STDOUT_FILENO

---

AUTHORS
doc/CMakeLists.txt

With CMake 4+, the initial CMake run fails with
CMake Error at doc/CMakeLists.txt:18 (ADD_DEPENDENCIES):
The dependency target "doc-c" of target "doc" does not exist.
in case Doxygen is not installed on the system, since non-existent dependencies
are not ignored anymore (see [0]). Rectify that by making sure that we only add
the dependency in case Doxygen has been found.
[0]: https://cmake.org/cmake/help/latest/policy/CMP0046.html

cmake: Allow builds without Doxygen being present with CMake 4+

---

createrepo_c.spec

Fedora is going to move from cmake with make to cmake with ninja <https://fedoraproject.org/wiki/Changes/CMake_ninja_default>. That would break building an RPM package from our spec file because the new %cmake macro won't produce Makefiles:
+ make -j8 'RPM_OPT_FLAGS=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer' make: *** No targets specified and …

spec: Consistently use CMake RPM macros
