- src/parsehdr.c
This should avoid situations where a package provides and requires same
capability (a dependency) with different versions but createrepo_c
strip the require down (because it already saw it in provides).
This should fix the issue in a better way than PR #68
> Consider versions during dep filtering for requires/provides (Issue #67)

- README.md
> Change location of drpm code to new address in GitHub

- src/mergerepo_c.c
I have service which merges multiple repositories together. The repositories live on NFS which is mounted in `/mnt/odcs/repos` in backend. The final merged repositories are stored in `/mnt/odcs/public`. I therefore call `mergerepo_c -o /mnt/odcs/public -r /mnt/odcs/repos/foo -r /mnt/odcs/repos/bar -r ...`.
The issue is that merged repository should be accessed using HTTP on certain domain (for example http://odcs.fedoraproject.org/composes/), but the merged metadata contains location base set to `file:///mnt/odcs/public`, so the merged repo is not useful.
This PR adds new `--repo-prefix` and `--repo-prefix-url` options to address this. In my case, I can use `--repo-prefix /mnt/odcs/public --repo-prefix-url http://odcs.fedoraproject.org/composes` and the `/mnt/odcs/public` in repopath is …
> Add mergerepo_c --repo-prefix-search and --repo-prefix-replace.

- README.md
Addressing
```
2:
2: ======================================================================
2: ERROR: test_crfile_xz_compression (tests.test_crfile.TestCaseCrFile)
2: ----------------------------------------------------------------------
2: Traceback (most recent call last):
2:   File "/src/tests/python/tests/test_crfile.py", line 104, in test_crfile_xz_compression
2:     p = subprocess.Popen(["unxz", "--stdout", path], stdout=subprocess.PIPE)
2:   File "/usr/lib64/python3.7/subprocess.py", line 775, in __init__
2:     restore_signals, start_new_session)
2:   File "/usr/lib64/python3.7/subprocess.py", line 1522, in _execute_child
2:     raise child_exception_type(errno_num, err_msg, err_filename)
2: FileNotFoundError: [Errno 2] No such file or directory: 'unxz': 'unxz'
2:
2: …
```
> For make test, xz and zchunk (not just *-devel) are required.

- src/mergerepo_c.c
- src/xml_dump.c
- src/xml_dump.h
- src/xml_dump_primary.c
- tests/CMakeLists.txt
- tests/test_xml_dump.c
- tests/test_xml_dump_primary.c
mergerepo_c: Unify url creation when adding package
> mergerepo_c: Consistently produce valid URLs by prepending protocol. (RhBug:1632121)

- src/xml_dump_updateinfo.c
- tests/python/tests/test_updateinfo.py
Also fixed indentation of the whole method and added tests for this case.
> Fix crash when dumping updateinfo and module is ommited (RhBug:1707981)

- src/createrepo_c.c
> Prevent exiting with 0 if errors occur while finalizing repodata.

- src/python/CMakeLists.txt
- src/python/__init__.py
- src/python/createrepo_cmodule.c
- src/python/updatecollection-py.c
- src/python/updatecollectionmodule-py.c
- src/python/updatecollectionmodule-py.h
- src/updateinfo.c
- src/updateinfo.h
- src/xml_dump_updateinfo.c
- src/xml_parser_internal.h
- src/xml_parser_updateinfo.c
- tests/fixtures.h
- tests/python/tests/test_updatecollection.py
- tests/python/tests/test_updatecollectionmodule.py
- tests/python/tests/test_updateinfo.py
- tests/test_xml_parser_updateinfo.c
- tests/testdata/updateinfo_files/updateinfo_03.xml
Waiting for exception to be approved.
> Add support for modular errata (RhBug:1656584)

- src/dumper_thread.c
As was pointed out here: https://github.com/rpm-software-management/createrepo_c/commit/3018bc474f4eab634d176d5150b87ff29751fd65#r35631776 my previous implementation was simply wrong and using `g_mkstemp_full` is better anyway.
https://bugzilla.redhat.com/show_bug.cgi?id=1686812
> Fix file mode for cache (RhBug:1686812)

- src/python/updatecollectionpackage-py.c
- src/python/updaterecord-py.c
- src/updateinfo.c
- src/updateinfo.h
- src/xml_dump_updateinfo.c
- src/xml_parser_updateinfo.c
- tests/python/tests/test_updateinfo.py
- tests/python/tests/test_updaterecord.py
- tests/test_xml_parser_updateinfo.c
- tests/testdata/updateinfo_files/updateinfo_01.xml
- tests/testdata/updateinfo_files/updateinfo_03.xml
I have also extended existing unit tests with this new field.
https://bugzilla.redhat.com/show_bug.cgi?id=1772466
> Add reboot_suggested to UpdateRecord (RhBug:1772466)

- src/createrepo_c.c
> Skip directory matching --exclude right away.

- examples/python/contenthash_calculation.py
- examples/python/repodata_parsing.py
- examples/python/repomd_parsing.py
- examples/python/simple_createrepo.py
- examples/python/simple_modifyrepo.py
- examples/python/updateinfo_gen_01.py
- examples/python/updateinfo_gen_02.py
- examples/python/updateinfo_parsing.py
This should help with https://github.com/rpm-software-management/createrepo_c/issues/194
> Update examples to python3

- src/compression_wrapper.c
- src/createrepo_c.c
- src/load_metadata.c
- src/mergerepo_c.c
- src/python/load_metadata-py.c
- src/xml_dump.c
- src/xml_file.c
- src/xml_parser_updateinfo.c
https://bugzilla.redhat.com/show_bug.cgi?id=1789707
> Fix handful of issues reported by covscans (RhBug:1789707)

- CMakeLists.txt
- cmake/Modules/FindGLIB2.cmake
- cmake/Modules/FindGTHREAD2.cmake
- src/createrepo_shared.c
- src/misc.c
Hi!
I got a couple of errors while trying to compile on FreeBSD. First is that `SIGPOLL` is not defined there, and second is that glib libraries are installed to the `/usr/local/lib` directory that was not searched by linker. Please pull fixes for these issues.
> Fix build on FreeBSD

- src/python/updaterecord-py.c
To resolve https://github.com/rpm-software-management/createrepo_c/issues/206
> Replace PyLong_AsSize_t with more supported alternative

- src/compression_wrapper.c
- src/deltarpms.c
- src/dumper_thread.c
- src/koji.c
- src/parsehdr.c
- src/python/compression_wrapper-py.c
- src/python/contentstat-py.c
- src/python/load_metadata-py.c
- src/python/locate_metadata-py.c
- src/python/package-py.c
- src/python/repomd-py.c
- src/python/repomdrecord-py.c
- src/python/sqlite-py.c
- src/python/updatecollection-py.c
- src/python/updatecollectionmodule-py.c
- src/python/updatecollectionpackage-py.c
- src/python/updateinfo-py.c
- src/python/updaterecord-py.c
- src/python/updatereference-py.c
- src/python/xml_file-py.c
- src/xml_dump_updateinfo.c
I went through debug compiler warnings, covscans and PVS-Studio Analysis Results (from https://github.com/rpm-software-management/createrepo_c/issues/203) and fixed some of the issues reported.
> Fix various warnings

- src/python/updaterecord-py.c
- src/xml_parser_filelists.c
- src/xml_parser_internal.h
- src/xml_parser_other.c
- src/xml_parser_primary.c
- src/xml_parser_repomd.c
- src/xml_parser_updateinfo.c
- tests/python/tests/fixtures.py
- tests/python/tests/test_updateinfo.py
- tests/testdata/updateinfo_files/updateinfo_03.xml
This fixes a couple of problems I have caused when working on createrepo_c.
Discovered by covscans.
> Additional fixes for various issues discovered by static analysis

- createrepo_c.spec
= changelog =
resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1863376
> spec: Fix building with new cmake macros

- CMakeLists.txt
- createrepo_c.spec
Build with drpm only if specified.
https://bugzilla.redhat.com/show_bug.cgi?id=1914828
Disable delta rpms tests on fedora: https://github.com/rpm-software-management/ci-dnf-stack/pull/934
> Disable drpm support by default (RhBug:1914828)

- src/python/updaterecord-py.c
- tests/python/tests/test_updaterecord.py
https://bugzilla.redhat.com/show_bug.cgi?id=1921715
Simple unittest included.
> Setting updated/issued_date to None doesn't produce garbage values (RhBug:1921715)

- src/python/xml_file-py.c
> Fix segmentation fault when taking str() of closed file

- .github/workflows/ci-python.yml
- .github/workflows/release-python.yml
- MANIFEST.in
Source packages only, since manylinux wheels are still [broken](https://github.com/rpm-software-management/createrepo_c/issues/145#issuecomment-792322897)
> Upload packages to PyPI on release

- src/python/sqlite-py.c
- src/python/xml_file-py.c
- tests/python/tests/test_sqlite.py
- tests/python/tests/test_xml_file.py
https://bugzilla.redhat.com/show_bug.cgi?id=1913465
> Allow taking __repr__ (__str__) of closed xmlfile and sqlite (RhBug:1913465)

- .github/workflows/release-python.yml
https://pypi.org/help/#apitoken
> Fix capitalization of __token__, lower case is required by pypi

- doc/createrepo_c.8
- src/compression_wrapper.c
- src/createrepo_c.c
- src/deltarpms.c
- src/load_metadata.c
- src/mergerepo_c.c
- src/metadata_internal.h
- src/misc.c
- src/repomd.c
- src/sqliterepo_c.c
- src/threads.c
- src/xml_file.c
for: https://github.com/rpm-software-management/createrepo_c/issues/263
> Compressed modular metadata and memory leaks

- src/createrepo_c.c
Libmodulemd errors out when dumping empty index. This can happen if
running with just `--update` (no `--keep-all-metadata`) and old repo
has modules metadata which habe been removed in the meantime.
Test: https://github.com/rpm-software-management/ci-dnf-stack/pull/1027
> Track if merger is empty and don't try to dump index if it is

- src/package.c
- src/python/xml_parser-py.c
- src/xml_parser_main_metadata_together.c
> Fix lifetime issues

- src/repomd.c
These are the two changes suggested here: https://github.com/rpm-software-management/createrepo_c/pull/271/files#r703194629
> Fix a bug in cr_repomd_record_compress_and_fill()

- src/createrepo_c.c
- src/dumper_thread.c
- src/mergerepo_c.c
- src/misc.c
- src/misc.h
- src/sqliterepo_c.c
- src/xml_file.c
For: https://github.com/rpm-software-management/createrepo_c/issues/266
> Use copy+delete fallback when moving of a dir fails

- createrepo_c.spec
https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1
> use SPDX format for license

- src/misc.c
This code is pretty opaque unless you have a good knowledge of the RPM file format, so let's add some comments so it's more clear.
Moved cr_header_byte_range() to parsepkg.c as it's essentially doing package parsing, just manually.  But I can drop that commit if it doesn't make sense.
> Add comments to cr_get_header_byte_range()

- src/python/repomdrecord-py.c
> Note checksum_type parameter in the docs for RepomdRecord.fill()

- src/createrepo_c.c
Create just "group" repomd record, no compression suffix. Do not include uncompressed groupfile in metadata.
Additionally it is now possible to specify compressed groupfile as the input.
This is for: https://fedoraproject.org/wiki/Changes/createrepo_c_1.0.0
> Unify groupfile handling with other metadata types

- src/python/createrepo_c/__init__.py
Follow up: https://github.com/rpm-software-management/createrepo_c/issues/360
> Add note for future filists changes

- src/cmd_parser.c
I started using createrepo_c recently. I noticed a typo in the help text, so I thought I'd fix it. It looked like zck handling was missing altogether, so I added that in, too.
- Fix help text mixing up file extensions and compression methods
- Add zck method handling
- Put zck help text and parsing in `#ifdef WITH_ZCHUNK`
> Fix compression help text, zck handling

- src/mergerepo_c.c
- src/modifyrepo_shared.c
> mergerepo_c and modifyrepo_c now make "pretty" indented xml
